
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Dec 04 19:47:16 IST 2012
//----------------------------------------------------

package IC.Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 52;
  public static final int PLUSPLUS = 46;
  public static final int LCBR = 8;
  public static final int LTE = 29;
  public static final int INTEGER = 3;
  public static final int CONTINUE = 51;
  public static final int SEMI = 37;
  public static final int INT = 21;
  public static final int MINUS = 30;
  public static final int STATIC = 38;
  public static final int LT = 28;
  public static final int LP = 4;
  public static final int COMMA = 12;
  public static final int CLASS = 23;
  public static final int FirstDot = 56;
  public static final int MULTIPLYEQUAL = 50;
  public static final int RP = 5;
  public static final int SecondDot = 55;
  public static final int PLUS = 35;
  public static final int MULTIPLY = 32;
  public static final int QUOTE = 40;
  public static final int ASSIGN = 2;
  public static final int IF = 20;
  public static final int THIS = 41;
  public static final int DOT = 54;
  public static final int ID = 19;
  public static final int EOF = 0;
  public static final int BOOLEAN = 10;
  public static final int DIVIDEEQUAL = 53;
  public static final int MINUSMINUS = 47;
  public static final int RETURN = 36;
  public static final int RCBR = 9;
  public static final int LB = 6;
  public static final int LAND = 22;
  public static final int EQUAL = 13;
  public static final int TRUE = 42;
  public static final int NEW = 25;
  public static final int error = 1;
  public static final int RB = 7;
  public static final int LOR = 27;
  public static final int NULL = 34;
  public static final int PLUSEQUAL = 48;
  public static final int MOD = 31;
  public static final int BREAK = 11;
  public static final int VOID = 43;
  public static final int GTE = 18;
  public static final int ELSE = 15;
  public static final int MINUSEQUAL = 49;
  public static final int WHILE = 44;
  public static final int NEQUAL = 33;
  public static final int CLASS_ID = 45;
  public static final int EXTENDS = 14;
  public static final int STRING = 39;
  public static final int LNEG = 26;
  public static final int FALSE = 16;
  public static final int GT = 17;
  public static final int LENGTH = 24;
}

