
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Nov 28 19:13:31 IST 2012
//----------------------------------------------------

package IC.Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INTEGER = 3;
  public static final int ASSIGN = 2;
  public static final int EOF = 0;
  public static final int error = 1;
}

