
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Nov 30 10:36:53 IST 2012
//----------------------------------------------------

package IC.Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 53;
  public static final int PLUSPLUS = 47;
  public static final int LCBR = 8;
  public static final int LTE = 30;
  public static final int INTEGER = 3;
  public static final int CONTINUE = 52;
  public static final int SEMI = 38;
  public static final int INT = 22;
  public static final int MINUS = 31;
  public static final int STATIC = 39;
  public static final int LT = 29;
  public static final int LP = 4;
  public static final int COMMA = 12;
  public static final int CLASS = 24;
  public static final int MULTIPLYEQUAL = 51;
  public static final int RP = 5;
  public static final int PLUS = 36;
  public static final int MULTIPLY = 33;
  public static final int QUOTE = 41;
  public static final int IF = 21;
  public static final int ASSIGN = 2;
  public static final int THIS = 42;
  public static final int ID = 20;
  public static final int DOT = 13;
  public static final int BOOLEAN = 10;
  public static final int EOF = 0;
  public static final int DIVIDEEQUAL = 54;
  public static final int MINUSMINUS = 48;
  public static final int RETURN = 37;
  public static final int LAND = 23;
  public static final int RCBR = 9;
  public static final int LB = 6;
  public static final int EQUAL = 14;
  public static final int TRUE = 43;
  public static final int NEW = 26;
  public static final int error = 1;
  public static final int RB = 7;
  public static final int LOR = 28;
  public static final int NULL = 35;
  public static final int PLUSEQUAL = 49;
  public static final int MOD = 32;
  public static final int BREAK = 11;
  public static final int VOID = 44;
  public static final int GTE = 19;
  public static final int ELSE = 16;
  public static final int MINUSEQUAL = 50;
  public static final int WHILE = 45;
  public static final int NEQUAL = 34;
  public static final int CLASS_ID = 46;
  public static final int EXTENDS = 15;
  public static final int STRING = 40;
  public static final int LNEG = 27;
  public static final int FALSE = 17;
  public static final int GT = 18;
  public static final int LENGTH = 25;
}

