
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Nov 28 20:07:17 IST 2012
//----------------------------------------------------

package IC.Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LCBR = 4;
  public static final int SEMI = 11;
  public static final int INT = 14;
  public static final int STATIC = 6;
  public static final int LP = 9;
  public static final int COMMA = 17;
  public static final int CLASS = 2;
  public static final int RP = 10;
  public static final int ID = 8;
  public static final int BOOLEAN = 15;
  public static final int EOF = 0;
  public static final int LB = 12;
  public static final int RCBR = 5;
  public static final int error = 1;
  public static final int RB = 13;
  public static final int VOID = 7;
  public static final int CLASS_ID = 3;
  public static final int STRING = 16;
}

